server:
  port: 8080

spring:
  data:
    mongodb:
      # Replace <db_password> with your Atlas user's password (URL-encode special characters).
      uri: "spring:
  data:
   mongodb:
   uri: "mongodb+srv://raymondlhm:MyP%40ssw0rd@chelf.qcqicee.mongodb.net/?retryWrites=true&w=majority&appName=chelf"
